Allow hook type to be extended by the ambient
florian-lefebvre/astro-integration-kit pull request #87
Opened 2024-03-20 11:54 UTC by Fryuni

The logic is now compatible with any subtype of the hooks, which makes the code work even when the types were augmented externally.

2024-03-20 13:35 UTC, jdtjenkins commented on docs/src/content/docs/core/define-integration.mdx
> +Some official Astro tools, like [`@astrojs/db`](https://docs.astro.build/en/guides/integrations-guide/db/), define new integration hooks that are not built into Astro core. AIK, by default, don't int
```suggestion
Some official Astro integrations, like [`@astrojs/db`](https://docs.astro.build/en/guides/integrations-guide/db/), define new integration hooks that are not built into Astro core. Astro Integration Kit does not integrate with those hooks by default as they are optional.
```

2024-03-20 13:44 UTC, jdtjenkins commented on docs/src/content/docs/core/define-integration.mdx
> +
Might be worth having a heading here so we can easily link people to the specific `db` section.

`### @astrojs/db`

2024-03-20 13:44 UTC, jdtjenkins commented on package/src/extra/db.d.ts
> +declare namespace AIK {
Bit of a nitpick, but how do we feel about this being namespace` AIK` and not `AstroIntegrationKit` ?

2024-03-20 14:34 UTC, florian-lefebvre commented on docs/src/content/docs/core/define-integration.mdx
> +            "astro:db:setup": ({extendDb}) => {
```suggestion
            "astro:db:setup": ({ extendDb }) => {
```

2024-03-20 17:20 UTC, florian-lefebvre reviewed
My remaining review still stands!

2024-03-20 17:47 UTC, florian-lefebvre requested changes
Can you update the breaking changes docs as well?

2024-03-21 11:45 UTC, Fryuni commented
> Can you update the breaking changes docs as well?

It's not breaking though…

2024-03-21 11:55 UTC, florian-lefebvre commented
Oh I thought so my bad!

2024-03-21 11:56 UTC, florian-lefebvre requested changes
We just need a changeset and we're good to go!

2024-03-21 14:34 UTC, jdtjenkins approved these changes
This is one of the most beautiful PRs I've ever seen in my life

2024-03-21 14:41 UTC, florian-lefebvre approved these changes

2024-03-21 16:20 UTC, jdtjenkins approved these changes

2024-03-21 17:08 UTC, florian-lefebvre requested changes

2024-03-21 17:08 UTC, florian-lefebvre commented on package/package.json
> +		"dist"
```suggestion
		"dist",
		"types"
```

2024-03-21 17:26 UTC, florian-lefebvre approved these changes

2024-03-21 17:28 UTC, merged